In [19]:
import pandas as pd
df = pd.read_csv('iris_data.csv', decimal=',')
df

     Sepal length  Sepal width  Petal length  Petal width       Species
0             5.1          3.5           1.4          0.2     I. setosa
1             4.9          3.0           1.4          0.2     I. setosa
2             4.7          3.2           1.3          0.2     I. setosa
3             4.6          3.1           1.5          0.2     I. setosa
4             5.0          3.6           1.4          0.2     I. setosa
..            ...          ...           ...          ...           ...
145           6.7          3.0           5.2          2.3  I. virginica
146           6.3          2.5           5.0          1.9  I. virginica
147           6.5          3.0           5.2          2.0  I. virginica
148           6.2          3.4           5.4          2.3  I. virginica
149           5.9          3.0           5.1          1.8  I. virginica

[150 rows x 5 columns]

In [20]:
df.drop(columns=['Petal length', 'Petal width'], inplace=True)
df.set_index(['Species'], inplace=True)
df

              Sepal length  Sepal width
Species
I. setosa              5.1          3.5
I. setosa              4.9          3.0
I. setosa              4.7          3.2
I. setosa              4.6          3.1
I. setosa              5.0          3.6
...                    ...          ...
I. virginica           6.7          3.0
I. virginica           6.3          2.5
I. virginica           6.5          3.0
I. virginica           6.2          3.4
I. virginica           5.9          3.0

[150 rows x 2 columns]

In [34]:
import matplotlib.pyplot as plt
species = df.index.unique()
species_1 = df.where(df.index == species[0])
species_1
plt.scatter(df['Sepal length'], df['Sepal width'], c='red')

ValueError: Array conditional must be same shape as self